name: Build, Test, and Deploy Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      #  Checkout code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      #  Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run basic build & test
      - name: Run build and tests
        run: |
          echo "⚙️ Building Next.js app..."
          npm run build
          echo "✅ Build successful!"
          # Optional: add a simple test script in package.json if you want
          # npm test

      #  Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #  Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=ompraksh2929/nextjswexaai
          docker build -t $IMAGE_NAME:latest .

      # Run container for verification
      - name: Verify Docker container runs
        run: |
          IMAGE_NAME=ompraksh2929/nextjswexaai:latest
          docker run -d -p 3000:3000 --name app-test $IMAGE_NAME
          echo "⏳ Waiting for app to start..."
          sleep 10
          echo "🔍 Checking app health..."
          curl -f http://localhost:3000 || (echo "❌ App test failed" && exit 1)
          echo "✅ App is running fine!"
          docker stop app-test
          docker rm app-test

      
